require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GradeSheetsController do

  # This should return the minimal set of attributes required to create a valid
  # GradeSheet. As you add validations to GradeSheet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:user=>stub_model(User), 
     :exercise=>stub_model(Exercise),
     :src_code=>"test",
     :tests=>"{:test=>'a'}"}
  end

  describe "GET index" do
    it "assigns all grade_sheets as @grade_sheets" do
      grade_sheet = GradeSheet.create! valid_attributes
      get :index
      assigns(:grade_sheets).should eq([grade_sheet])
    end
  end

  describe "GET show" do
    it "assigns the requested grade_sheet as @grade_sheet" do
      grade_sheet = GradeSheet.create! valid_attributes
      get :show, :id => grade_sheet.id.to_s
      assigns(:grade_sheet).should eq(grade_sheet)
    end
  end

  describe "GET new" do
    it "assigns a new grade_sheet as @grade_sheet" do
      get :new
      assigns(:grade_sheet).should be_a_new(GradeSheet)
    end
  end

  describe "GET edit" do
    it "assigns the requested grade_sheet as @grade_sheet" do
      grade_sheet = GradeSheet.create! valid_attributes
      get :edit, :id => grade_sheet.id.to_s
      assigns(:grade_sheet).should eq(grade_sheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GradeSheet" do
        expect {
          post :create, :grade_sheet => valid_attributes
        }.to change(GradeSheet, :count).by(1)
      end

      it "assigns a newly created grade_sheet as @grade_sheet" do
        post :create, :grade_sheet => valid_attributes
        assigns(:grade_sheet).should be_a(GradeSheet)
        assigns(:grade_sheet).should be_persisted
      end

      it "redirects to the created grade_sheet" do
        post :create, :grade_sheet => valid_attributes
        response.should redirect_to(GradeSheet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grade_sheet as @grade_sheet" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeSheet.any_instance.stub(:save).and_return(false)
        post :create, :grade_sheet => {}
        assigns(:grade_sheet).should be_a_new(GradeSheet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeSheet.any_instance.stub(:save).and_return(false)
        post :create, :grade_sheet => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grade_sheet" do
        grade_sheet = GradeSheet.create! valid_attributes
        # Assuming there are no other grade_sheets in the database, this
        # specifies that the GradeSheet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GradeSheet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => grade_sheet.id, :grade_sheet => {'these' => 'params'}
      end

      it "assigns the requested grade_sheet as @grade_sheet" do
        grade_sheet = GradeSheet.create! valid_attributes
        put :update, :id => grade_sheet.id, :grade_sheet => valid_attributes
        assigns(:grade_sheet).should eq(grade_sheet)
      end

      it "redirects to the grade_sheet" do
        grade_sheet = GradeSheet.create! valid_attributes
        put :update, :id => grade_sheet.id, :grade_sheet => valid_attributes
        response.should redirect_to(grade_sheet)
      end
    end

    describe "with invalid params" do
      it "assigns the grade_sheet as @grade_sheet" do
        grade_sheet = GradeSheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeSheet.any_instance.stub(:save).and_return(false)
        put :update, :id => grade_sheet.id.to_s, :grade_sheet => {}
        assigns(:grade_sheet).should eq(grade_sheet)
      end

      it "re-renders the 'edit' template" do
        grade_sheet = GradeSheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeSheet.any_instance.stub(:save).and_return(false)
        put :update, :id => grade_sheet.id.to_s, :grade_sheet => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grade_sheet" do
      grade_sheet = GradeSheet.create! valid_attributes
      expect {
        delete :destroy, :id => grade_sheet.id.to_s
      }.to change(GradeSheet, :count).by(-1)
    end

    it "redirects to the grade_sheets list" do
      grade_sheet = GradeSheet.create! valid_attributes
      delete :destroy, :id => grade_sheet.id.to_s
      response.should redirect_to(grade_sheets_url)
    end
  end

end
